apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwce-sample
  labels:
    app: bwce-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bwce-sample
  template:
    metadata:
      labels:
        app: bwce-sample
      namespace: default
    spec:
      containers:
      - name: bwce-sample
        image: abhay1607/testapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        env:
        - name: APP_CONFIG_PROFILE
          value: docker
