apiVersion: v1
kind: Service
metadata:
  name: bwce-sample-service
  namespace: default
spec:
  selector:
    app: bwce-sample
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
